### ISSUE TITLE
Question about  RSHighlightable

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#155]
Why `RSHighlightable>>doHighlightShapes: shapes` is not written as:

```Smalltalk
RSHighlightable>>doHighlightShapes: shapes
       shapes do: [ :s | self doHighlight: s]
```
? 
Names of the methods `doHighlightShapes:` and `doHighlight:` would suggest such a behavior...

**Comment by bergel** [comment]
Maybe you can give a method comment about this

**Comment by akevalion** [comment]
RSHighlightable can be used in application like an object instance attribute, not only like an interaction. RSSearchInCanvas uses an instance of RSHighlightable.

For that reason `doHighlightShapes:` can be used with shapes defined by the user (for example a custom search).

Both methods `doHighlight:`and `doHighlightShapes:` reset the previous highlighted shapes.
Because of that I can not use `doHighlight:` in `doHighlightShapes:`.
