### ISSUE TITLE
Is there a bug with the zooming?

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#222]
Any idea why the polyline is disappearing when I zoom in/out?

Here is a video: https://www.dropbox.com/s/wgphm0kr4o6a2c2/BugInRoassal3.mov?dl=0

**Comment by akevalion** [comment]
I think that you are using a composite for that.
Remember after using a composite with `add:` use `adjustToChildren`. or use `RSGroup` with `asShape` after adding the RSChart on it.

This happens, because RSAthensMorph only shows shapes on the visible area, if your composite does not have a good encompassing rectangle this will be hidden.

Example
```Smalltalk
canvas := RSCanvas new.
com := RSComposite new.

com add: (RSBox new
	size: 100;
	color: Color gray translucent;
	yourself).
canvas add: com.
canvas showEncompassingRectangles.
canvas @RSCanvasController.
```
Try to move the box out the visible area, you will see that you can hide the box.
![image](https://user-images.githubusercontent.com/10532890/81428616-838e0c80-912a-11ea-991a-4206d59ed1e9.png)

There are 2 solutions.

- use adjustToChildren for a good encompassing Rectangle for the composite.
- use a Quadtree in RSAthensMorph to get all the visible shapes, (even composite's children) on the visible  area.
