### ISSUE TITLE
QuadTree and Visualization content

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#3]
We should have two hierarchies: one defining the visualization content (DOM), and another for the rendering structure, based on QuadTree

**Comment by akevalion** [comment]
There is a new visualization that show an visual effect of quadtree `example13VisualizeQuatree`

![image](https://user-images.githubusercontent.com/10532890/61750246-d6046500-ad72-11e9-8163-45e2a9e9cc31.png)


but this is not implemented on TSAthensCanvas

**Comment by bergel** [comment]
Impressive. So, now we need to incorporate this in `TSAthensCanvas`

**Comment by akevalion** [comment]
We can use the quadtree to find the visible elements in the visible area area, with quatree we can find this in a fast way in order to draw only visible shapes.

But also maybe we can speed up the  time of each visualization in order to maybe in a visualization do not redraw all the visualization, only the changed element.

**Comment by akevalion** [comment]
This issue is not valid anymore, because Quadtree is a data structure for points. Roassal needs Rectangle tree (Rtree), because all its nodes have an encompassing rectangle or bounding box
