### ISSUE TITLE
Why RSMultilineLabelBuilder is in Interaction?

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#317]
Shouldn't it go to Shape instead?

**Comment by akevalion** [comment]
RSMultilineLabelBuilder is a utility class for popup, in order to create popup with several lines, specially for method source code.

Because of that, this class is part of Roassal3-Interactions package, also this class uses layouts. In order to avoid dependency from `Roassal3-Shapes` to `Roassal3-Layouts`, this class remains in `Roassal3-Interactions`

**Comment by akevalion** [comment]
Can we close this issue?

**Comment by bergel** [comment]
It seems that it can go to a dedicated package, with its strategies

**Comment by akevalion** [comment]
I have moved this class and its strategies to builders
