### ISSUE TITLE
Remove unused instance variables

### ISSUE THREAD

**Issue by Ducasse** [ObjectProfile/Roassal3#329]
UnusedVariableRemover new unusedVariables inspect

will be available soon in Pharo 90

Should do the same for class variables

**Comment by bergel** [comment]
hi!
How can we try this `UnusedVariableRemover` ?

**Comment by MarcusDenker** [comment]
What I do: I run the test testNoUnusedInstanceVariablesLeft and inspect the list of classes that should be empty

**Comment by astares** [comment]
Related to https://github.com/pharo-project/pharo/issues/8424 which is listing
RSAbstractContext
RSAbstractContainerBuilder
RSAbstractFlowLayout
RSAbstractLineLayout

@bergel 
see all details in https://github.com/pharo-project/pharo/issues/8189 

To query use:
````Smalltalk
 Smalltalk globals allBehaviors 
 		select: [ :each | each instanceVariables anySatisfy: [ :iv | iv isReferenced not] ]
``` 		
````Smalltalk
 Smalltalk globals allBehaviors 
 		select: [ :each | each classVariables anySatisfy: [ :iv | iv isReferenced not] ]
```
and then check for the Roassal ones.

You have to check one by one - because sometimes the tests require an ivar to exist. 
Then you can solve by adding a simple getter.

**Comment by akevalion** [comment]
Thank you for your feedback, currently I have used your code and I have removed the unused ivars.

Will be present in the next release

**Comment by astares** [comment]
@akevalion Thanks for picking up the topic. We should not wait too long to integrate this next release as we want to solve
https://github.com/pharo-project/pharo/issues/8189 to activate release tests so that we do not get new unused ivars introduced into the standard image and can prove that we stay clean.

**Comment by bergel** [comment]
Should be fixed! Thanks for the discussion
