### ISSUE TITLE
Roassal3-Benchmarks loads deprecated Scripting package

### ISSUE THREAD

**Issue by pavel-krivanek** [ObjectProfile/Roassal3#335]
Roassal3-Benchmarks loads SMark package as a dependency and it loads the Scripting package. Smark uses only ScriptingConsole from it which is a simple stream wrapper. The problem is that Scripting package is old and contains a lot of deprecated code. It even uses the old startup registration mechanism.

**Comment by tinchodias** [comment]
Hi. I think this issue is for https://github.com/tinchodias/RS3Benchmarks. Right?

I don't have now an image with the project installed, but I browsed the code in GH. 
This is the baseline:
https://github.com/tinchodias/RS3Benchmarks/blob/master/BaselineOfRS3Benchmarks/BaselineOfRS3Benchmarks.class.st

Which links to this baseline:
https://github.com/smarr/SMark/blob/v1.0.4/repository/BaselineOfSMark/BaselineOfSMark.class.st

I'm surprised that the baseline doesn't link to the ScriptingConsole that you mention. But I believe you... I'm sure if I install the project I would check what you reported.

**Comment by pavel-krivanek** [comment]
It is a dependency of SMark: https://github.com/smarr/SMark/blob/master/repository/BaselineOfSMark/BaselineOfSMark.class.st

**Comment by akevalion** [comment]
What is the status of this issue?

@tinchodias could we have a pair programming to review that on monday 15-feb?

Maybe we can move this issue to https://github.com/tinchodias/RS3Benchmarks.

**Comment by tinchodias** [comment]
I think I'll be able to pair-program on Monday afternoon. It belongs more
to the other repo, I agree.

**Comment by tinchodias** [comment]
Hi @pavel-krivanek did you have to do some workaround because of this issue? did you have an loading problem due to this legacy code? or it's a matter of reducing the load?


Today we did some analysis with @akevalion, and I will comment it here, for the record.


First, we explored the dependencies from Smark to Scripting package (using the tool in P9), and effectively looks small.

```
SMarkReporter class >>
defaultOutputDestination
	^ ScriptConsole
```

And it looked as it was not used by our code (only executed from an `initialize` but never used).

Second, to enforce this guess, we replaced `^ ScriptConsole` by `^ Trasncript` and just `^ nil` and no problem (we executed `RSBenchChartBuilder exampleFirstRenderings`).

**Comment by akevalion** [comment]
Is this issue still valid?

**Comment by pavel-krivanek** [comment]
Yes, the dependency is here. The initialization had troubles in Pharo 9

**Comment by akevalion** [comment]
Hello today, I review this issue with pharo 9.0, and I can not find any loading error, or any error with dependencies.

<img width="1350" alt="image" src="https://user-images.githubusercontent.com/10532890/195803359-ede3bd30-d062-4d7e-9de7-fecf017f5ac1.png">
