### ISSUE TITLE
Adding proper heatmaps

### ISSUE THREAD

**Issue by Inao0** [ObjectProfile/Roassal3#562]
## An example of heatmap :

![image](https://github.com/ObjectProfile/Roassal3/assets/37711386/2568ed88-425c-46d1-ba7e-7fdc999f6542)

## What is already existing : 
In Roassal there is the **`RSDSM`** (Dependency structural matrix) which is the closest thing to a heatmap.
There is also, in a package not loaded, **`RSHeatmap`** which is outdated and inherits directly from `Object` (Still works though). For now, the RSDSM name is quite cryptic and for someone looking for a heatmap, this is going to be hard to find.
 
## Differences in APIs : 
Expected APIs are different. 
This is the second example for RSDSM:
``` Smalltalk
example02Numbers
        | dsm |
	dsm := RSDSM new.
	dsm objectsX: (1 to: 10).
	dsm objectsY: (1 to: 10 by: 2).
	dsm dependency: [ :aValue | aValue // 2 ].
	^ dsm
```
Here we can see here that DSM takes objects, either one list for both axis or two different lists, and a dependency bloc that given an object will return which objects it depends on (either one object or a list of objects). Cells that are at the intersection of rows and columns will be colored. The colors can be altered by giving a block able to compute the color of a cell from a the tuple of the row object and column object.

In a heatmap, the expected API would be something like this:
``` Smalltalk
example
	| h |
	h := RSHeatmap new.
	h objectsX: #('A' 'B' 'C').
	h objectsY: #('tomato' 'pumpkin').
        h dataMatrix:  #(#(1 2 5) #(3 4 6)).
        ^ h dataMatrice
```
The objects on the axis could be only labels if it's simpler. We do not need the objects to compute dependencies, the color of a scale is a number inside the matrix and the position is already determined. 
Maybe the heatmap could take a block to calculate the value matrix, in this case, labels would not be enough, and objects would be required. 

## Default values
- There should be a default sequential palette and a diverging one.
- The extremum should by default be computed from the matrice, but the user should be able to set it manually, for example, to make sure that several heatmap have the same color scale.
- There should be a way to display the color scale. It should probably be activated by default.
- Another good option would optionally be to be able to show the value of each cell :
![image](https://github.com/ObjectProfile/Roassal3/assets/37711386/45630564-d6c6-4456-a259-2109973656e9)

Some more examples of heatmaps : https://chartio.com/learn/charts/heatmap-complete-guide/

**Comment by akevalion** [comment]
Hi, I have added class `RSHeatmap` in package `Roassal3-DSM` There are 3 new examples about this:
```st
| builder |
builder := RSHeatmap new.
builder objectsX: #('A' 'B' 'C').
builder objectsY: #('tomato' 'pumpkin').
builder dataMatrix: #(#(1 2 5) #(3 4 6)).
^ builder
```
<img width="473" alt="image" src="https://github.com/ObjectProfile/Roassal3/assets/10532890/eff402de-7469-4d7b-8b63-c419ae7013ee">

Example with months
<img width="944" alt="image" src="https://github.com/ObjectProfile/Roassal3/assets/10532890/0d15c8c3-090c-45fb-a7ad-f06291741d5b">

And with vegetables
<img width="488" alt="image" src="https://github.com/ObjectProfile/Roassal3/assets/10532890/2457c80f-fdc2-4dbd-9ce1-c049caaa607a">

# About these points
- There should be a default sequential palette and a diverging one. 
Yes by default there is a linear scale of colors, that you can use. but you can chage it into new one
```st
builder colorPalette: (NSScale linear range: {Color gray. Color purple muchDarker}).
```
- The extremum should by default be computed from the matrix, but the user should be able to set it manually, for example, to make sure that several heatmap have the same color scale.
Again you can change the color paletter, but the difference here. is that you have to put this color palette after `dataMatrix:` because that method computes the domain for the given matrix.
```st
builder dataMatrix: values.
builder colorPalette: (NSScale linear range: {Color gray. Color purple muchDarker}).
```
- There should be a way to display the color scale. It should probably be activated by default.
Because it is a subclass of RSDSM, you can use `color:aBlockOrColor`. By default is using the `colorPalette`
```st
builder color: [:matrixValue | Color random ].
```
- Another good option would optionally be to be able to show the value of each cell :
By default it is present and you can set the way to display each string, but If you want to disable this.
```st
builder shouldShowCellLabels: false.
```

**Comment by akevalion** [comment]
@Inao0 can we close this issue?

**Comment by Inao0** [comment]
Yes, perfect, thanks :)
