### ISSUE TITLE
Issue loading roassal3 on windows 10

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/Roassal3#90]
There is an error loading roassal3 on windows with pharo8 and pharo7 64 bits

**Comment by riverdusty** [comment]
> There is an error loading roassal3 on windows with pharo8 and pharo7 64 bits

What is the error? which version of Pharo7?

Loading github repos on 64bit pharo in 64bit windows 10 can cause image to crash

**Comment by bergel** [comment]
Thanks @riverdusty 
Next week we will have a windows machine to try this. We will be able to investigate this issue

**Comment by akevalion** [comment]
This was an error that one user reported on Aug 2019, it was related to loading athens in pharo, I do not have a windows 10 machine, to test it

**Comment by RainerWinkler** [comment]
I use Windows 10 and had many problems to install Roassal today.
This might be due to:
1. the following issue: https://github.com/pharo-project/pharo/issues/4437
It is solved by updating the virtual machine.
2. There may also be issues in Iceberg, after solving my main problems with point 1 I still was not able to install in Pharo 8.0. Maybe due to this error or something related: https://github.com/pharo-vcs/iceberg/issues/577

It may help when Windows 10 users are told in the introduction to update their virtual machines or ...

**Comment by fuhrmanator** [comment]
See the workaround I posted at https://github.com/pharo-project/pharo/issues/4437#issuecomment-586620625

**Comment by akevalion** [comment]
I have loaded Roassal3 on windows10 pharo 8 64 bits without errors

**Comment by bergel** [comment]
Feel free to reopen this issue in case the problem persists
